import { type OperationsWorkspaceData } from '@/team-workspace/operations';
import { type SalesWorkspaceData } from '@/team-workspace/sales';

const isoFromNow = (hours: number) =>
  new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();

export const salesReviewData: SalesWorkspaceData = {
  salespersonName: 'Abrar',
  meetings: [
    {
      id: 'meeting-aster',
      contactName: 'Nadia Rahman',
      companyName: 'Aster Logistics',
      startsAt: isoFromNow(2),
      durationMinutes: 30,
      timezoneLabel: 'Asia/Dhaka',
      kind: 'discovery',
      status: 'scheduled',
      preparationStatus: 'not-started',
      opportunityId: 'opportunity-aster',
    },
    {
      id: 'meeting-crescent',
      contactName: 'Imran Noor',
      companyName: 'Crescent Dental',
      startsAt: isoFromNow(26),
      durationMinutes: 45,
      timezoneLabel: 'Asia/Dhaka',
      kind: 'proposal',
      status: 'prepared',
      preparationStatus: 'ready',
      preparationSummary:
        'Confirm the pilot scope, implementation owner, and decision date.',
      opportunityId: 'opportunity-crescent',
    },
    {
      id: 'meeting-harborline',
      contactName: 'Lena Chowdhury',
      companyName: 'Harborline Software',
      startsAt: isoFromNow(-24),
      durationMinutes: 38,
      timezoneLabel: 'Asia/Dhaka',
      kind: 'follow-up',
      status: 'attended',
      preparationStatus: 'ready',
      opportunityId: 'opportunity-harborline',
      outcome: 'Lena approved the next delivery checkpoint for Thursday.',
    },
    {
      id: 'meeting-unverified',
      contactName: 'Sami Ahmed',
      companyName: 'Juniper Systems',
      startsAt: isoFromNow(-50),
      durationMinutes: 30,
      timezoneLabel: 'Asia/Dhaka',
      kind: 'qualification',
      status: 'outcome-missing',
      preparationStatus: 'not-started',
      opportunityId: 'opportunity-juniper',
    },
  ],
  opportunities: [
    {
      id: 'opportunity-aster',
      contactName: 'Nadia Rahman',
      companyName: 'Aster Logistics',
      stage: 'discovery',
      nextAction: 'Prepare partnership and ABM plan',
      nextActionDueAt: isoFromNow(1),
    },
    {
      id: 'opportunity-crescent',
      contactName: 'Imran Noor',
      companyName: 'Crescent Dental',
      stage: 'proposal',
      nextAction: 'Confirm pilot decision date',
      nextActionDueAt: isoFromNow(24),
    },
    {
      id: 'opportunity-harborline',
      contactName: 'Lena Chowdhury',
      companyName: 'Harborline Software',
      stage: 'won',
      nextAction: 'Complete the structured Operations handoff',
      nextActionDueAt: isoFromNow(4),
    },
    {
      id: 'opportunity-juniper',
      contactName: 'Sami Ahmed',
      companyName: 'Juniper Systems',
      stage: 'qualified',
    },
  ],
  followUps: [
    {
      id: 'follow-up-1',
      title: 'Send the agreed ABM plan',
      companyName: 'Aster Logistics',
      detail: 'Use the pricing they agreed on the last call.',
      dueAt: isoFromNow(-3),
      status: 'todo',
      opportunityId: 'opportunity-aster',
    },
    {
      id: 'follow-up-2',
      title: 'Confirm who joins the pilot review',
      companyName: 'Crescent Dental',
      detail: null,
      dueAt: isoFromNow(20),
      status: 'in-progress',
      opportunityId: 'opportunity-crescent',
    },
  ],
  coachingReviews: [
    {
      id: 'recording-harborline',
      meetingId: 'meeting-harborline',
      contactName: 'Lena Chowdhury',
      companyName: 'Harborline Software',
      occurredAt: isoFromNow(-24),
      transcriptStatus: 'available',
      summary:
        'The call established the delivery checkpoint, but the decision question came late.',
      strengths: [
        'Restated the client’s concern before suggesting the next step.',
        'Closed with a named owner and a specific day.',
      ],
      improvement: {
        title: 'Ask the decision question before presenting the delivery plan.',
      },
      evidence: [
        {
          id: 'evidence-harborline-1',
          timestampLabel: '18:42',
          observation:
            'The decision process was clarified only near the close.',
          excerpt:
            'Lena: Thursday works, but I need the implementation owner there too.',
        },
      ],
    },
    {
      id: 'meeting-unverified',
      meetingId: 'meeting-unverified',
      contactName: 'Sami Ahmed',
      companyName: 'Juniper Systems',
      occurredAt: isoFromNow(-50),
      transcriptStatus: 'missing',
    },
  ],
};

export const operationsReviewData: OperationsWorkspaceData = {
  viewer: { id: 'fahim-review', name: 'Fahim' },
  clients: [
    {
      id: 'client-harborline',
      name: 'Harborline Software',
      status: 'active',
      health: 'watch',
      ownerName: 'Fahim',
    },
    {
      id: 'client-crescent',
      name: 'Crescent Dental',
      status: 'onboarding',
      health: 'healthy',
      ownerName: 'Fahim',
    },
    {
      id: 'client-juniper',
      name: 'Juniper Systems',
      status: 'unknown',
      health: 'unknown',
      ownerName: null,
    },
  ],
  tasks: [
    {
      id: 'task-promise',
      title: 'Publish the Harborline weekly progress note',
      clientId: 'client-harborline',
      clientName: 'Harborline Software',
      ownerId: 'fahim-review',
      ownerName: 'Fahim',
      status: 'in-progress',
      priority: 'urgent',
      dueAt: isoFromNow(-5),
      isClientPromise: true,
      blockedReason: null,
      updatedAt: isoFromNow(-4),
      completionEvidence: null,
    },
    {
      id: 'task-blocker',
      title: 'QA the onboarding sequence',
      clientId: 'client-crescent',
      clientName: 'Crescent Dental',
      ownerId: 'fahim-review',
      ownerName: 'Fahim',
      status: 'blocked',
      priority: 'high',
      dueAt: isoFromNow(8),
      isClientPromise: false,
      blockedReason: 'Waiting for the approved campaign brief.',
      updatedAt: isoFromNow(-2),
      completionEvidence: null,
    },
    {
      id: 'task-routine',
      title: 'Prepare Thursday’s delivery review',
      clientId: 'client-harborline',
      clientName: 'Harborline Software',
      ownerId: 'fahim-review',
      ownerName: 'Fahim',
      status: 'todo',
      priority: 'normal',
      dueAt: isoFromNow(22),
      isClientPromise: false,
      blockedReason: null,
      updatedAt: isoFromNow(-1),
      completionEvidence: null,
    },
    {
      id: 'task-done',
      title: 'Create the Crescent Dental workspace',
      clientId: 'client-crescent',
      clientName: 'Crescent Dental',
      ownerId: 'fahim-review',
      ownerName: 'Fahim',
      status: 'done',
      priority: 'normal',
      dueAt: isoFromNow(-30),
      isClientPromise: true,
      blockedReason: null,
      updatedAt: isoFromNow(-26),
      completionEvidence: {
        summary: 'Workspace created and access verified with the client seat.',
        sourceRef: 'CRM task #MM-104',
        recordedAt: isoFromNow(-26),
        recordedBy: 'Fahim',
      },
    },
  ],
  meetings: [
    {
      id: 'ops-meeting-harborline',
      clientId: 'client-harborline',
      clientName: 'Harborline Software',
      title: 'Weekly delivery review',
      startsAt: isoFromNow(5),
      endsAt: isoFromNow(5.75),
      ownerName: 'Fahim',
      participants: ['Fahim', 'Lena Chowdhury'],
      purpose: 'Review delivered work, blockers, and the next commitment.',
      prepStatus: 'in-progress',
      prepSummary: 'Metrics are ready; blocker decision is still missing.',
      previousMeetingSummary:
        'Agreed to verify the implementation owner before Thursday.',
      joinUrl: 'https://meet.google.com/review-link',
      status: 'scheduled',
    },
    {
      id: 'ops-meeting-crescent',
      clientId: 'client-crescent',
      clientName: 'Crescent Dental',
      title: 'Onboarding checkpoint',
      startsAt: isoFromNow(29),
      endsAt: isoFromNow(29.5),
      ownerName: 'Fahim',
      participants: ['Fahim', 'Imran Noor'],
      purpose: 'Confirm the first campaign inputs and responsibilities.',
      prepStatus: 'not-started',
      prepSummary: null,
      previousMeetingSummary: null,
      joinUrl: null,
      status: 'scheduled',
    },
    {
      id: 'ops-meeting-juniper',
      clientId: 'client-juniper',
      clientName: 'Juniper Systems',
      title: 'Delivery discovery',
      startsAt: isoFromNow(-18),
      endsAt: isoFromNow(-17.5),
      ownerName: 'Fahim',
      participants: ['Fahim', 'Sami Ahmed'],
      purpose: 'Confirm the requested delivery sequence and internal owner.',
      prepStatus: 'ready',
      prepSummary: 'Questions and scope were prepared before the call.',
      previousMeetingSummary: null,
      joinUrl: null,
      status: 'outcome-missing',
    },
  ],
  updates: [
    {
      id: 'update-harborline',
      clientId: 'client-harborline',
      clientName: 'Harborline Software',
      summary: 'Delivery checkpoint agreed; implementation owner is pending.',
      status: 'verified',
      occurredAt: isoFromNow(-190),
      verifiedAt: isoFromNow(-190),
      verifiedBy: 'Fahim',
      evidenceRef: 'CRM note #FR8-221',
    },
    {
      id: 'update-crescent',
      clientId: 'client-crescent',
      clientName: 'Crescent Dental',
      summary: 'Client workspace access was tested successfully.',
      status: 'verified',
      occurredAt: isoFromNow(-20),
      verifiedAt: isoFromNow(-20),
      verifiedBy: 'Fahim',
      evidenceRef: 'CRM task #MM-104',
    },
  ],
  handoffs: [
    {
      id: 'handoff-aster',
      title: 'Aster Logistics partnership and ABM delivery',
      clientId: null,
      clientName: 'Aster Logistics',
      fromName: 'Abrar',
      toUserId: 'fahim-review',
      toName: 'Fahim',
      context:
        'Problem: protect YouTube content and identify regional broadcast partners. Scope: partnership plan and ABM rollout. Next commitment: implementation plan review.',
      createdAt: isoFromNow(-1),
      dueAt: isoFromNow(6),
      status: 'pending',
    },
  ],
};
